//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCM.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargerType
    {
        public ChargerType()
        {
            this.ConnectionInfoes = new HashSet<ConnectionInfo>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Comments { get; set; }
        public bool IsFastChargeCapable { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual ICollection<ConnectionInfo> ConnectionInfoes { get; set; }
    }
}
