//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCM.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.UserSubscriptions = new HashSet<UserSubscription>();
            this.Statistics = new HashSet<Statistic>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string ISOCode { get; set; }
        public string ContinentCode { get; set; }
    
        public virtual ICollection<UserSubscription> UserSubscriptions { get; set; }
        public virtual ICollection<Statistic> Statistics { get; set; }
    }
}
