//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCM.Core.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OCMEntities : DbContext
    {
        public OCMEntities()
            : base("name=OCMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressInfo> AddressInfoList { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<ChargePoint> ChargePoints { get; set; }
        public virtual DbSet<ChargerType> ChargerTypes { get; set; }
        public virtual DbSet<CheckinStatusType> CheckinStatusTypes { get; set; }
        public virtual DbSet<ConnectionInfo> ConnectionInfoList { get; set; }
        public virtual DbSet<ConnectionType> ConnectionTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CurrentType> CurrentTypes { get; set; }
        public virtual DbSet<DataProvider> DataProviders { get; set; }
        public virtual DbSet<DataProviderStatusType> DataProviderStatusTypes { get; set; }
        public virtual DbSet<DataType> DataTypes { get; set; }
        public virtual DbSet<EditQueueItem> EditQueueItems { get; set; }
        public virtual DbSet<EntityType> EntityTypes { get; set; }
        public virtual DbSet<MetadataField> MetadataFields { get; set; }
        public virtual DbSet<MetadataGroup> MetadataGroups { get; set; }
        public virtual DbSet<MetadataValue> MetadataValues { get; set; }
        public virtual DbSet<Operator> Operators { get; set; }
        public virtual DbSet<StatusType> StatusTypes { get; set; }
        public virtual DbSet<SubmissionStatusType> SubmissionStatusTypes { get; set; }
        public virtual DbSet<SystemConfig> SystemConfigs { get; set; }
        public virtual DbSet<UsageType> UsageTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserComment> UserComments { get; set; }
        public virtual DbSet<UserCommentType> UserCommentTypes { get; set; }
        public virtual DbSet<MediaItem> MediaItems { get; set; }
        public virtual DbSet<MetadataFieldOption> MetadataFieldOptions { get; set; }
        public virtual DbSet<RegisteredApplication> RegisteredApplications { get; set; }
        public virtual DbSet<UserSubscription> UserSubscriptions { get; set; }
        public virtual DbSet<UserChargingRequest> UserChargingRequests { get; set; }
    }
}
