//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCM.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataProviderUser
    {
        public int ID { get; set; }
        public int DataProviderID { get; set; }
        public int UserID { get; set; }
        public bool IsDataProviderAdmin { get; set; }
    
        public virtual DataProvider DataProvider { get; set; }
        public virtual User User { get; set; }
    }
}
