//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCM.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditQueueItem
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Comment { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<int> ProcessedByUserID { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public string EditData { get; set; }
        public string PreviousData { get; set; }
        public Nullable<int> EntityID { get; set; }
        public Nullable<short> EntityTypeID { get; set; }
    
        public virtual User User { get; set; }
        public virtual User ProcessedByUser { get; set; }
        public virtual EntityType EntityType { get; set; }
    }
}
