//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCM.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetadataFieldOption
    {
        public MetadataFieldOption()
        {
            this.MetadataValues = new HashSet<MetadataValue>();
        }
    
        public int ID { get; set; }
        public int MetadataFieldID { get; set; }
        public string Title { get; set; }
    
        public virtual MetadataField MetadataField { get; set; }
        public virtual ICollection<MetadataValue> MetadataValues { get; set; }
    }
}
