//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCM.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetadataField
    {
        public MetadataField()
        {
            this.MetadataValues = new HashSet<MetadataValue>();
            this.MetadataFieldOptions = new HashSet<MetadataFieldOption>();
        }
    
        public int ID { get; set; }
        public int MetadataGroupID { get; set; }
        public string Title { get; set; }
        public byte DataTypeID { get; set; }
    
        public virtual DataType DataType { get; set; }
        public virtual MetadataGroup MetadataGroup { get; set; }
        public virtual ICollection<MetadataValue> MetadataValues { get; set; }
        public virtual ICollection<MetadataFieldOption> MetadataFieldOptions { get; set; }
    }
}
