//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCM.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public System.Guid ID { get; set; }
        public string StatTypeCode { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int NumItems { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual User User { get; set; }
    }
}
