//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCM.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionStatusType
    {
        public SubmissionStatusType()
        {
            this.ChargePoints = new HashSet<ChargePoint>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public bool IsLive { get; set; }
    
        public virtual ICollection<ChargePoint> ChargePoints { get; set; }
    }
}
