//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCM.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfig
    {
        public string ConfigKeyName { get; set; }
        public string ConfigValue { get; set; }
        public Nullable<byte> DataTypeID { get; set; }
    
        public virtual DataType DataType { get; set; }
    }
}
