//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCM.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubscription
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> DistanceKM { get; set; }
        public string FilterSettings { get; set; }
        public Nullable<System.DateTime> DateLastNotified { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool NotifyPOIAdditions { get; set; }
        public bool NotifyPOIEdits { get; set; }
        public bool NotifyComments { get; set; }
        public bool NotifyMedia { get; set; }
        public bool NotifyEmergencyChargingRequests { get; set; }
        public bool NotifyGeneralChargingRequests { get; set; }
        public bool NotifyPOIUpdates { get; set; }
        public int NotificationFrequencyMins { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual User User { get; set; }
    }
}
