name: .NET Build

on: [push]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build with dotnet
      run: dotnet build Website\OCM.Web\OCM.Web.csproj --configuration Release
